### ISSUE TITLE
Fix Error on Motivator Route

### ISSUE THREAD

**Issue by alexfritsch10** [mindtastic/motivator-service#11]
Right now, I get back an error from the motivator service as soon as I issue an GET request on the /motivator or the base (localhost:4545/) route. This is the error, I receive: 
```
2022-07-04 14:50:01.478 UTC [30] FATAL:  database "motivator" does not exist
headcoach          | SequelizeConnectionError: database "motivator" does not exist
headcoach          |     at Client._connectionCallback (/app/node_modules/sequelize/src/dialects/postgres/connection-manager.js:189:24)
headcoach          |     at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
headcoach          |     at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
headcoach          |     at Connection.emit (node:events:537:28)
headcoach          |     at Connection.emit (node:domain:482:12)
headcoach          |     at /app/node_modules/pg/lib/connection.js:114:12
headcoach          |     at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:104:9)
headcoach          |     at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
headcoach          |     at Socket.emit (node:events:537:28)
headcoach          |     at Socket.emit (node:domain:482:12)
```

**Comment by jgraeger** [comment]
Please use the `docker compose`environment for local development. We configured it to work on every major platform and to reload the code (and recompile the typescript) on every code file change.

If you don't want to use the `docker compose`, setup your local dev environment accordingly (Installing PGSQL, creating the right user). However I don't recommend the latter.
